version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:8
  working_directory: ~/project/react-pure-loaders

attach_workspace: &attach_workspace
  attach_workspace:
      at: ~/project

install_steps: &install_steps
  steps:
    - checkout
    - *attach_workspace
    - restore_cache:
        name: Restore node_modules cache
        keys:
          - node-modules-{{ .Branch }}-{{ checksum "package.json" }}
          - node-modules-{{ .Branch }}-
          - node-modules-
    - run:
        name: Install Dependencies
        command: npm install
    - save_cache:
        name: Save node_modules cache
        key: node-modules-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - node_modules/
    - persist_to_workspace:
        root: ~/project
        paths:
          - react-pure-loaders

test_steps: &test_steps
  steps:
    - checkout
    - restore_cache:
        key: node-modules-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Install Local Packages
        command: npm install
    - run:
        name: Test Suite
        command: npm run test:ci

jobs:
  install:
    <<: *docker_defaults
    <<: *install_steps

  npmvet:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: NPM Vet
          command: |
            sudo npm i -g npmvet
            npm run verify:npmvet

  eslint:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: ESLint
          command: npm run eslint

  test-node-8:
    working_directory: ~/react-pure-loaders
    docker:
    <<: *docker_defaults
    <<: *test_steps

  test-node-10:
    docker:
      - image: circleci/node:8
    <<: *test_steps

  test-node-11:
    working_directory: ~/react-pure-loaders
    docker:
      - image: circleci/node:11
    <<: *test_steps

  test-node-12:
    working_directory: ~/react-pure-loaders
    docker:
      - image: circleci/node:12
    <<: *test_steps

  coverage:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: Coverage
          command: |
            npm run test:coverage:ci
            npm run test:coverage:codecov

  build-typescript:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: Build JavaScript
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - react-pure-loaders

  semantic-release:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  version: 2
  install-test-build-and-publish:
    jobs:
      - install
      - npmvet:
          requires:
            - install
      - eslint:
          requires:
            - npmvet
      - test-node-8:
          requires:
            - eslint
      - test-node-10:
          requires:
            - eslint
      - test-node-11:
          requires:
            - eslint
      - test-node-12:
          requires:
            - eslint
      - coverage:
          requires:
            - test-node-8
            - test-node-10
            - test-node-11
            - test-node-12
      - build-typescript:
          requires:
            - coverage
      - semantic-release:
          requires:
            - build-typescript
